create table svm( employer_name varchar(10),age int,department varchar(10),address varchar(20));
select * from svm;
insert into svm3 values('abi',20,'mech','trichy');
select * from svm where department='ece'and address='trichy';
select * from svm where department='ece'or address='trichy';
select * from svm where NOT address='vaduvur';
select * from svm order by employer_name ;
select * from svm order by employer_name asc ;
select * from svm order by employer_name desc;
select * from svm where address is not null;
update svm set department='civil' where age=13;
delete from svm where employer_name ='asrin';
select * from svm;
select  * from svm limit 2;
select * from svm where age>=16;
select min(age) from svm where address='vaduvur';
select max(age) from svm where address='vaduvur';
select count(address) from svm; 
select avg(age) from svm;
select * from svm where address like'v%';
select * from svm where address like'%y';
select * from svm where address like'_a%';
select * from svm where address like'v__%';
select * from svm where address like'v%i';
select * from svm where address IN('trichy');		 	
select * from svm where  age between 13 and 16;
select * from svm2.s2 join svm3.s3 on s3.employer_name=s2.employer_name;